// Sanitation Plugin - Highest Priority Post-Stream
// Created: January 2025
// Purpose: Remove watermarks and unwanted artifacts from LLM output

import { Plugin, PluginContext, PluginResult, PluginPhase, PluginPriority } from '../types'

/**
 * Sanitation Plugin - Priority 0 (runs first)
 * Removes zero-width characters, watermarks, and unwanted formatting
 */
export const sanitationPlugin: Plugin = {
  id: 'sanitation-output',
  name: 'Output Sanitation',
  description: 'Remove watermarks and artifacts from LLM output',
  version: '1.0.0',

  phase: PluginPhase.POST_STREAM,
  priority: PluginPriority.CRITICAL, // Priority 0 - runs first

  enabled: true,

  async execute(context: PluginContext): Promise<PluginResult> {
    const startTime = Date.now()

    try {
      if (!context.content) {
        return {
          success: true,
          content: '',
          metrics: {
            duration: Date.now() - startTime
          }
        }
      }

      let cleaned = context.content

      // Remove zero-width characters (potential watermarks)
      cleaned = cleaned.replace(/[\u200B-\u200D\uFEFF]/g, '')

      // Remove directional marks
      cleaned = cleaned.replace(/\u200E|\u200F/g, '')

      // Remove other invisible characters
      cleaned = cleaned.replace(/[\u2060-\u206F]/g, '')

      // Normalize whitespace
      cleaned = cleaned.replace(/\s+/g, ' ')

      // Remove leading/trailing whitespace
      cleaned = cleaned.trim()

      // Remove any remaining control characters
      cleaned = cleaned.replace(/[\x00-\x1F\x7F]/g, '')

      // Check for common AI artifacts
      const artifacts = [
        /\[AI-generated\]/gi,
        /\[Generated by .+?\]/gi,
        /^AI:/gm,
        /^Assistant:/gm,
        /^Claude:/gm,
        /^ChatGPT:/gm,
        /\[Start of .+? response\]/gi,
        /\[End of .+? response\]/gi,
      ]

      for (const artifact of artifacts) {
        cleaned = cleaned.replace(artifact, '')
      }

      // Final cleanup
      cleaned = cleaned.trim()

      return {
        success: true,
        content: cleaned,
        metrics: {
          duration: Date.now() - startTime,
        },
        data: {
          originalLength: context.content.length,
          cleanedLength: cleaned.length,
          charactersRemoved: context.content.length - cleaned.length
        }
      }
    } catch (error) {
      return {
        success: false,
        error: `Sanitation failed: ${error}`,
        content: context.content, // Return original on failure
        metrics: {
          duration: Date.now() - startTime
        }
      }
    }
  },

  async validate(context: PluginContext): Promise<boolean> {
    return context.content !== undefined && context.content !== null
  }
}