import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import {
  getSystemPrompt,
  buildPrompt,
  sanitize,
  type GenerateInput
} from '@/lib/ai/prompts/linkedin-connection'
import { createClient } from '@/lib/supabase/server'
import { z } from 'zod'

// Initialize Anthropic client
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
})

// Rate limiting: 30 requests per day per IP
const rateLimits = new Map<string, { count: number; reset: number }>()

function checkRateLimit(ip: string): { allowed: boolean; remainingRequests?: number; resetTime?: number } {
  const now = Date.now()
  const limit = rateLimits.get(ip)
  const dailyLimit = 30

  if (limit && limit.reset > now && limit.count >= dailyLimit) {
    return {
      allowed: false,
      remainingRequests: 0,
      resetTime: limit.reset
    }
  }

  if (!limit || limit.reset <= now) {
    rateLimits.set(ip, { count: 1, reset: now + 86400000 }) // 24 hours
    return {
      allowed: true,
      remainingRequests: dailyLimit - 1,
      resetTime: now + 86400000
    }
  } else {
    limit.count++
    return {
      allowed: true,
      remainingRequests: Math.max(0, dailyLimit - limit.count),
      resetTime: limit.reset
    }
  }
}

// Request validation schema - Updated to handle null values from Chrome extension
const generateRequestSchema = z.object({
  profile: z.object({
    name: z.string(),
    headline: z.string().nullish(),
    location: z.string().nullish(),
    about: z.string().nullish(),
    experiences: z.array(z.object({
      title: z.string(),
      company: z.string().nullish()
    })).nullish(),
    recentPosts: z.array(z.string()).nullish(),
    skills: z.array(z.string()).nullish(),
    profileUrl: z.string().url()
  }),
  resume: z.string().nullish().default(''),
  jd: z.string().nullish().default(''), // Job description
  category: z.enum(['linkedin_connection', 'cold_email', 'linkedin_inmail']),
  intent: z.enum(['networking', 'referral', 'mentorship', 'job_inquiry']).nullish().default('networking'),
  acceptedExamples: z.array(z.string()).nullish().default([])
})

type GenerateRequest = z.infer<typeof generateRequestSchema>

export async function POST(request: NextRequest) {
  try {
    // Rate limiting check
    const ip = request.headers.get('x-forwarded-for') ||
              request.headers.get('x-real-ip') ||
              'unknown'

    const rateCheck = checkRateLimit(ip)
    if (!rateCheck.allowed) {
      return NextResponse.json({
        error: 'Daily limit reached',
        message: 'You have exceeded the 30 requests per day limit. Please try again tomorrow.',
        resetTime: rateCheck.resetTime
      }, {
        status: 429,
        headers: {
          'X-RateLimit-Limit': '30',
          'X-RateLimit-Remaining': '0',
          'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
        }
      })
    }

    // Simple API key authentication for extension
    const authHeader = request.headers.get('x-api-key')
    if (!authHeader || authHeader !== process.env.EXTENSION_API_KEY) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Parse and validate request
    const body = await request.json()
    const validatedData = generateRequestSchema.parse(body)

    const { profile, resume, jd, category, intent, acceptedExamples } = validatedData

    // Use new prompt system
    const systemPrompt = getSystemPrompt(category)
    const userPrompt = buildPrompt({
      profile,
      resume: resume || '',
      jd: jd || undefined,
      category,
      intent: intent || 'networking',
      acceptedExamples: acceptedExamples || []
    })

    // Generate content using Claude
    const startTime = Date.now()
    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 600, // Enough for LinkedIn message or email
      temperature: 0.8, // Slightly creative for personalization
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    })

    const processingTime = Date.now() - startTime
    const rawContent = response.content[0]?.type === 'text'
      ? response.content[0].text
      : ''

    if (!rawContent) {
      throw new Error('No content generated by Claude')
    }

    // Sanitize output with negative lexicon
    const sanitizedContent = sanitize(rawContent)

    // Log usage for monitoring
    const tokenUsage = response.usage
    console.log(`Extension generation: ${tokenUsage.input_tokens + tokenUsage.output_tokens} tokens, ${processingTime}ms`)

    // Parse response based on category with validation
    if (category === 'cold_email' || category === 'linkedin_inmail') {
      try {
        // Parse JSON response (new format)
        const parsed = JSON.parse(sanitizedContent)

        // Validate structure and limits
        if (parsed.subject_line && parsed.body) {
          const wordCount = parsed.word_count || countWords(parsed.body)

          // Check limits based on category
          const maxWords = category === 'cold_email' ? 150 : 120
          const minWords = category === 'cold_email' ? 100 : 80

          if (wordCount > maxWords) {
            console.warn(`${category} exceeds word limit: ${wordCount} > ${maxWords}`)
            // Truncate body to fit limits
            parsed.body = truncateToWordLimit(parsed.body, maxWords)
          }

          return NextResponse.json({
            success: true,
            subject_line: parsed.subject_line,
            body: parsed.body,
            category,
            word_count: countWords(parsed.body),
            character_count: parsed.body.length,
            validation: {
              word_limit_passed: countWords(parsed.body) <= maxWords,
              sanitization_applied: rawContent !== sanitizedContent
            },
            usage: tokenUsage,
            processingTime
          }, {
            headers: {
              'X-RateLimit-Limit': '30',
              'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
              'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
            }
          })
        }
      } catch (parseError) {
        console.warn('Failed to parse JSON response, treating as plain text')
      }

      // Fallback for non-JSON responses
      const subject = extractSubjectFromText(sanitizedContent)
      const body = extractBodyFromText(sanitizedContent)

      return NextResponse.json({
        success: true,
        subject_line: subject,
        body: body,
        category,
        word_count: countWords(body),
        character_count: body.length,
        validation: {
          word_limit_passed: false, // Unknown format doesn't guarantee limits
          sanitization_applied: rawContent !== sanitizedContent,
          fallback_parsing: true
        },
        usage: tokenUsage,
        processingTime
      }, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
          'X-RateLimit-Limit': '30',
          'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
          'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
        }
      })
    }

    // For LinkedIn connections - apply smart character limit with sentence-aware trimming
    let finalContent = sanitizedContent
    let wasTruncated = false
    const originalLength = sanitizedContent.length

    // Hard limit at 290 chars to leave buffer for LinkedIn's 300 char limit
    if (finalContent.length > 290) {
      console.warn(`LinkedIn connection exceeds character limit: ${finalContent.length} > 290`)

      // Smart trimming: try to cut at last complete sentence
      let trimmedContent = finalContent.substring(0, 290)
      const lastPeriod = trimmedContent.lastIndexOf('.')
      const lastQuestion = trimmedContent.lastIndexOf('?')
      const lastExclamation = trimmedContent.lastIndexOf('!')
      const cutoff = Math.max(lastPeriod, lastQuestion, lastExclamation)

      // Only cut at sentence end if we have a reasonable sentence (>150 chars)
      if (cutoff > 150) {
        finalContent = trimmedContent.substring(0, cutoff + 1)
      } else {
        // Fallback: hard cut with ellipsis
        finalContent = trimmedContent.substring(0, 287) + '...'
      }

      wasTruncated = true
    }

    return NextResponse.json({
      success: true,
      body: finalContent,
      category,
      character_count: finalContent.length,
      validation: {
        character_limit_passed: true,
        original_length: originalLength,
        truncated: wasTruncated,
        sanitization_applied: rawContent !== sanitizedContent
      },
      usage: tokenUsage,
      processingTime
    }, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
        'X-RateLimit-Limit': '30',
        'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
        'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
      }
    })

    return NextResponse.json({
      success: true,
      body: sanitizedContent,
      category,
      character_count: charCount,
      validation: {
        character_limit_passed: true,
        sanitization_applied: rawContent !== sanitizedContent
      },
      usage: tokenUsage,
      processingTime
    }, {
      headers: {
        'X-RateLimit-Limit': '30',
        'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
        'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
      }
    })

  } catch (error) {
    console.error('Extension generation error:', error)

    // Handle specific errors
    if (error instanceof z.ZodError) {
      return NextResponse.json({
        success: false,
        error: 'Invalid request data',
        details: error.errors[0]?.message
      }, { status: 400 })
    }

    if (error instanceof Anthropic.APIError) {
      if (error.status === 401) {
        return NextResponse.json({
          success: false,
          error: 'Anthropic API authentication failed'
        }, { status: 500 })
      }

      if (error.status === 429) {
        return NextResponse.json({
          success: false,
          error: 'Rate limit exceeded, please try again later'
        }, { status: 429 })
      }
    }

    return NextResponse.json({
      success: false,
      error: 'Failed to generate content'
    }, { status: 500 })
  }
}

// Utility functions for validation
function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(word => word.length > 0).length
}

function truncateToWordLimit(text: string, maxWords: number): string {
  const words = text.trim().split(/\s+/)
  if (words.length <= maxWords) {
    return text
  }
  return words.slice(0, maxWords).join(' ')
}

function extractSubjectFromText(content: string): string {
  // Look for "Subject:" pattern or use first line
  const subjectMatch = content.match(/(?:Subject|SUBJECT):\s*(.+)/i)
  if (subjectMatch) {
    return subjectMatch[1].trim()
  }

  // Use first line if no subject pattern found
  const firstLine = content.split('\n')[0]?.trim()
  return firstLine || 'Quick connect'
}

function extractBodyFromText(content: string): string {
  // Remove subject line if present
  let body = content.replace(/(?:Subject|SUBJECT):\s*(.+)\n?/i, '')

  // Clean up and return body
  return body.trim()
}

// GET endpoint for testing with API key validation
export async function GET(request: NextRequest) {
  try {
    // Rate limiting check (same as POST)
    const ip = request.headers.get('x-forwarded-for') ||
              request.headers.get('x-real-ip') ||
              'unknown'

    const rateCheck = checkRateLimit(ip)
    if (!rateCheck.allowed) {
      return NextResponse.json({
        error: 'Daily limit reached',
        message: 'You have exceeded the 30 requests per day limit. Please try again tomorrow.',
        resetTime: rateCheck.resetTime
      }, {
        status: 429,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
          'X-RateLimit-Limit': '30',
          'X-RateLimit-Remaining': '0',
          'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
        }
      })
    }

    // API key authentication (same as POST)
    const authHeader = request.headers.get('x-api-key')
    console.log('GET Request - Received API key:', authHeader?.substring(0, 10) + '...')
    console.log('GET Request - Expected API key:', process.env.EXTENSION_API_KEY?.substring(0, 10) + '...')

    if (!authHeader || authHeader !== process.env.EXTENSION_API_KEY) {
      return NextResponse.json({
        error: 'Unauthorized',
        message: 'Valid API key required for access'
      }, {
        status: 401,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, x-api-key'
        }
      })
    }

    // Success response with API key validated
    return NextResponse.json({
      service: 'Ascendia Extension API',
      version: '1.0.0',
      endpoints: {
        generate: 'POST /api/extension/generate'
      },
      status: 'healthy',
      authenticated: true
    }, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
        'X-RateLimit-Limit': '30',
        'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
        'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
      }
    })

  } catch (error) {
    console.error('GET endpoint error:', error)
    return NextResponse.json({
      error: 'Internal server error'
    }, {
      status: 500,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, x-api-key'
      }
    })
  }
}

// OPTIONS handler for CORS preflight
export async function OPTIONS() {
  return new Response(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
      'Access-Control-Max-Age': '86400', // 24 hours
    },
  })
}