import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import {
  getSystemPrompt,
  buildPrompt,
  sanitize,
  type GenerateInput
} from '@/lib/ai/prompts/linkedin-connection'
import { sanitizeForLinkedIn } from '@/lib/ai/sanitizer'
import { createClient } from '@/lib/supabase/server'
import { z } from 'zod'

// Initialize Anthropic client
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
})

// Rate limiting: 30 requests per day per IP
const rateLimits = new Map<string, { count: number; reset: number }>()

function checkRateLimit(ip: string): { allowed: boolean; remainingRequests?: number; resetTime?: number } {
  const now = Date.now()
  const limit = rateLimits.get(ip)
  const dailyLimit = 30

  if (limit && limit.reset > now && limit.count >= dailyLimit) {
    return {
      allowed: false,
      remainingRequests: 0,
      resetTime: limit.reset
    }
  }

  if (!limit || limit.reset <= now) {
    rateLimits.set(ip, { count: 1, reset: now + 86400000 }) // 24 hours
    return {
      allowed: true,
      remainingRequests: dailyLimit - 1,
      resetTime: now + 86400000
    }
  } else {
    limit.count++
    return {
      allowed: true,
      remainingRequests: Math.max(0, dailyLimit - limit.count),
      resetTime: limit.reset
    }
  }
}

// Request validation schema - Updated to handle null values from Chrome extension
const generateRequestSchema = z.object({
  profile: z.object({
    name: z.string(),
    headline: z.string().nullish(),
    location: z.string().nullish(),
    about: z.string().nullish(),
    experiences: z.array(z.object({
      title: z.string(),
      company: z.string().nullish()
    })).nullish(),
    recentPosts: z.array(z.string()).nullish(),
    skills: z.array(z.string()).nullish(),
    profileUrl: z.string().url()
  }),
  resume: z.string().nullish().default(''),
  jd: z.string().nullish().default(''), // Job description
  category: z.enum(['linkedin_connection', 'cold_email', 'linkedin_inmail']),
  intent: z.enum(['networking', 'referral', 'mentorship', 'job_inquiry']).nullish().default('networking'),
  acceptedExamples: z.array(z.string()).nullish().default([])
})

type GenerateRequest = z.infer<typeof generateRequestSchema>

export async function POST(request: NextRequest) {
  try {
    // Rate limiting check
    const ip = request.headers.get('x-forwarded-for') ||
      request.headers.get('x-real-ip') ||
      'unknown'

    const rateCheck = checkRateLimit(ip)
    if (!rateCheck.allowed) {
      return NextResponse.json({
        error: 'Daily limit reached',
        message: 'You have exceeded the 30 requests per day limit. Please try again tomorrow.',
        resetTime: rateCheck.resetTime
      }, {
        status: 429,
        headers: {
          'X-RateLimit-Limit': '30',
          'X-RateLimit-Remaining': '0',
          'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
        }
      })
    }

    // Simple API key authentication for extension
    const authHeader = request.headers.get('x-api-key')
    if (!authHeader || authHeader !== process.env.EXTENSION_API_KEY) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Parse and validate request
    const body = await request.json()
    const validatedData = generateRequestSchema.parse(body)

    const { profile, resume, jd, category, intent, acceptedExamples } = validatedData

    // Use new prompt system
    const systemPrompt = getSystemPrompt(category)
    const userPrompt = buildPrompt({
      profile: {
        name: profile.name,
        headline: profile.headline || '',
        location: profile.location || '',
        about: profile.about || '',
        experiences: (profile.experiences || []).map(e => ({ title: e.title, company: e.company || '' })),
        recentPosts: profile.recentPosts || [],
        skills: profile.skills || []
      },
      resume: resume || '',
      jd: jd || '',
      category,
      intent: intent || 'networking',
      acceptedExamples: acceptedExamples || []
    })

    // Generate content using Claude
    const startTime = Date.now()
    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 600, // Enough for LinkedIn message or email
      temperature: 0.8, // Slightly creative for personalization
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    })

    const processingTime = Date.now() - startTime
    const rawContent = response.content[0]?.type === 'text'
      ? response.content[0].text
      : ''

    if (!rawContent) {
      throw new Error('No content generated by Claude')
    }

    // Log usage for monitoring
    const tokenUsage = response.usage
    console.log(`Extension generation: ${tokenUsage.input_tokens + tokenUsage.output_tokens} tokens, ${processingTime}ms`)

    // Parse response based on category with validation
    if (category === 'cold_email' || category === 'linkedin_inmail') {
      try {
        // Parse JSON response FIRST (before sanitization to avoid corrupting JSON structure)
        const parsed = JSON.parse(rawContent)

        // Validate structure and limits
        if (parsed.subject_line && parsed.body) {
          // Apply AI fingerprint detection and sanitization to individual fields
          const basicSubjectSanitization = sanitize(parsed.subject_line)
          const basicBodySanitization = sanitize(parsed.body)

          // Enhanced sanitization with AI fingerprint detection for LinkedIn
          const enhancedSubjectSanitization = await sanitizeForLinkedIn(basicSubjectSanitization)
          const enhancedBodySanitization = await sanitizeForLinkedIn(basicBodySanitization)

          const sanitizedSubject = enhancedSubjectSanitization.success ? enhancedSubjectSanitization.sanitizedContent : basicSubjectSanitization
          const sanitizedBody = enhancedBodySanitization.success ? enhancedBodySanitization.sanitizedContent : basicBodySanitization

          // Log AI detection results for monitoring (check both fields)
          const subjectHasAI = enhancedSubjectSanitization.isAIGenerated
          const bodyHasAI = enhancedBodySanitization.isAIGenerated

          if (subjectHasAI || bodyHasAI) {
            console.warn('AI fingerprints detected in Chrome extension generation:', {
              subject: subjectHasAI ? {
                confidence: enhancedSubjectSanitization.aiFingerprints?.confidence,
                patterns: enhancedSubjectSanitization.aiFingerprints?.detectedPatterns,
                authenticityScore: enhancedSubjectSanitization.authenticityScore
              } : null,
              body: bodyHasAI ? {
                confidence: enhancedBodySanitization.aiFingerprints?.confidence,
                patterns: enhancedBodySanitization.aiFingerprints?.detectedPatterns,
                authenticityScore: enhancedBodySanitization.authenticityScore
              } : null,
              category: validatedData.category
            })
          }

          const wordCount = parsed.word_count || countWords(sanitizedBody)

          // Check limits based on category
          const maxWords = category === 'cold_email' ? 150 : 120
          const minWords = category === 'cold_email' ? 100 : 80

          let finalBody = sanitizedBody
          if (wordCount > maxWords) {
            console.warn(`${category} exceeds word limit: ${wordCount} > ${maxWords}`)
            // Truncate body to fit limits
            finalBody = truncateToWordLimit(sanitizedBody, maxWords)
          }

          return NextResponse.json({
            success: true,
            subject_line: sanitizedSubject,
            body: finalBody,
            category,
            word_count: countWords(finalBody),
            character_count: finalBody.length,
            validation: {
              word_limit_passed: countWords(finalBody) <= maxWords,
              sanitization_applied: parsed.subject_line !== sanitizedSubject || parsed.body !== sanitizedBody,
              ai_patterns_detected: subjectHasAI || bodyHasAI,
              json_parsing_successful: true
            },
            usage: tokenUsage,
            processingTime
          }, {
            headers: {
              'X-RateLimit-Limit': '30',
              'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
              'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
            }
          })
        }
      } catch (parseError) {
        console.warn('Failed to parse JSON response, attempting fallback sanitization and parsing:', parseError)

        // Fallback: Apply basic sanitization to raw content first, then try text extraction
        const basicSanitization = sanitize(rawContent)
        const enhancedSanitization = await sanitizeForLinkedIn(basicSanitization)
        const sanitizedContent = enhancedSanitization.success ? enhancedSanitization.sanitizedContent : basicSanitization

        // Log AI detection results for monitoring
        if (enhancedSanitization.isAIGenerated) {
          console.warn('AI fingerprints detected in fallback processing:', {
            confidence: enhancedSanitization.aiFingerprints?.confidence,
            patterns: enhancedSanitization.aiFingerprints?.detectedPatterns,
            authenticityScore: enhancedSanitization.authenticityScore,
            category: validatedData.category
          })
        }

        const subject = extractSubjectFromText(sanitizedContent)
        const body = extractBodyFromText(sanitizedContent)

        return NextResponse.json({
          success: true,
          subject_line: subject,
          body: body,
          category,
          word_count: countWords(body),
          character_count: body.length,
          validation: {
            word_limit_passed: false, // Unknown format doesn't guarantee limits
            sanitization_applied: rawContent !== sanitizedContent,
            ai_patterns_detected: enhancedSanitization.isAIGenerated,
            json_parsing_successful: false,
            fallback_parsing: true
          },
          usage: tokenUsage,
          processingTime
        }, {
          headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
            'X-RateLimit-Limit': '30',
            'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
            'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
          }
        })
      }
    }

    // For LinkedIn connections - apply AI fingerprint detection and sanitization
    const basicSanitization = sanitize(rawContent)
    const enhancedSanitization = await sanitizeForLinkedIn(basicSanitization)
    const sanitizedContent = enhancedSanitization.success ? enhancedSanitization.sanitizedContent : basicSanitization

    // Log AI detection results for monitoring
    if (enhancedSanitization.isAIGenerated) {
      console.warn('AI fingerprints detected in LinkedIn connection generation:', {
        confidence: enhancedSanitization.aiFingerprints?.confidence,
        patterns: enhancedSanitization.aiFingerprints?.detectedPatterns,
        authenticityScore: enhancedSanitization.authenticityScore,
        category: validatedData.category
      })
    }

    // Apply smart character limit preserving the OPEN sentence
    let finalContent = sanitizedContent
    let wasTruncated = false
    const originalLength = sanitizedContent.length

    // LinkedIn's actual limit is 300 chars
    if (finalContent.length > 300) {
      console.warn(`LinkedIn connection exceeds character limit: ${finalContent.length} > 300`)

      // Smart trimming: PRESERVE the last sentence (the OPEN/question) — it's the most important
      // Strategy: split into sentences, try removing/shortening earlier sentences first
      const sentences = finalContent.match(/[^.!?]+[.!?]+/g) || [finalContent]

      if (sentences.length >= 3) {
        // Try dropping sentence 1 (HOOK) and keeping BRIDGE + OPEN
        const withoutHook = sentences.slice(1).join(' ').trim()
        if (withoutHook.length <= 300) {
          finalContent = withoutHook
          wasTruncated = true
        } else {
          // Even without HOOK it's too long — keep just the last sentence (OPEN)
          const lastSentence = sentences[sentences.length - 1]?.trim() ?? ''
          if (lastSentence.length > 0 && lastSentence.length <= 300) {
            finalContent = lastSentence
            wasTruncated = true
          } else {
            // Last resort: hard cut at 297 + ellipsis
            finalContent = finalContent.substring(0, 297) + '...'
            wasTruncated = true
          }
        }
      } else if (sentences.length === 2) {
        // Only 2 sentences — try trimming the first one
        const secondSentence = sentences[1]?.trim() ?? ''
        const firstTrimmed = (sentences[0] ?? '').substring(0, 300 - secondSentence.length - 2).trim()
        const combined = firstTrimmed + '. ' + secondSentence
        if (combined.length <= 300) {
          finalContent = combined
          wasTruncated = true
        } else {
          finalContent = finalContent.substring(0, 297) + '...'
          wasTruncated = true
        }
      } else {
        // Single run-on sentence — hard cut
        finalContent = finalContent.substring(0, 297) + '...'
        wasTruncated = true
      }
    }

    return NextResponse.json({
      success: true,
      body: finalContent,
      category,
      character_count: finalContent.length,
      validation: {
        character_limit_passed: true,
        original_length: originalLength,
        truncated: wasTruncated,
        sanitization_applied: rawContent !== sanitizedContent
      },
      usage: tokenUsage,
      processingTime
    }, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
        'X-RateLimit-Limit': '30',
        'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
        'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
      }
    })

  } catch (error) {
    console.error('Extension generation error:', error)

    // Handle specific errors
    if (error instanceof z.ZodError) {
      return NextResponse.json({
        success: false,
        error: 'Invalid request data',
        details: error.errors[0]?.message
      }, { status: 400 })
    }

    if (error instanceof Anthropic.APIError) {
      if (error.status === 401) {
        return NextResponse.json({
          success: false,
          error: 'Anthropic API authentication failed'
        }, { status: 500 })
      }

      if (error.status === 429) {
        return NextResponse.json({
          success: false,
          error: 'Rate limit exceeded, please try again later'
        }, { status: 429 })
      }
    }

    return NextResponse.json({
      success: false,
      error: 'Failed to generate content'
    }, { status: 500 })
  }
}

// Utility functions for validation
function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(word => word.length > 0).length
}

function truncateToWordLimit(text: string, maxWords: number): string {
  const words = text.trim().split(/\s+/)
  if (words.length <= maxWords) {
    return text
  }
  return words.slice(0, maxWords).join(' ')
}

function extractSubjectFromText(content: string): string {
  // Look for "Subject:" pattern or use first line
  const subjectMatch = content.match(/(?:Subject|SUBJECT):\s*(.+)/i)
  if (subjectMatch) {
    return subjectMatch[1].trim()
  }

  // Use first line if no subject pattern found
  const firstLine = content.split('\n')[0]?.trim()
  return firstLine || 'Quick connect'
}

function extractBodyFromText(content: string): string {
  // Remove subject line if present
  let body = content.replace(/(?:Subject|SUBJECT):\s*(.+)\n?/i, '')

  // Clean up and return body
  return body.trim()
}

// GET endpoint for testing with API key validation
export async function GET(request: NextRequest) {
  try {
    // Rate limiting check (same as POST)
    const ip = request.headers.get('x-forwarded-for') ||
      request.headers.get('x-real-ip') ||
      'unknown'

    const rateCheck = checkRateLimit(ip)
    if (!rateCheck.allowed) {
      return NextResponse.json({
        error: 'Daily limit reached',
        message: 'You have exceeded the 30 requests per day limit. Please try again tomorrow.',
        resetTime: rateCheck.resetTime
      }, {
        status: 429,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
          'X-RateLimit-Limit': '30',
          'X-RateLimit-Remaining': '0',
          'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
        }
      })
    }

    // API key authentication (same as POST)
    const authHeader = request.headers.get('x-api-key')
    console.log('GET Request - Received API key:', authHeader?.substring(0, 10) + '...')
    console.log('GET Request - Expected API key:', process.env.EXTENSION_API_KEY?.substring(0, 10) + '...')

    if (!authHeader || authHeader !== process.env.EXTENSION_API_KEY) {
      return NextResponse.json({
        error: 'Unauthorized',
        message: 'Valid API key required for access'
      }, {
        status: 401,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, x-api-key'
        }
      })
    }

    // Success response with API key validated
    return NextResponse.json({
      service: 'Ascendia Extension API',
      version: '1.0.0',
      endpoints: {
        generate: 'POST /api/extension/generate'
      },
      status: 'healthy',
      authenticated: true
    }, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
        'X-RateLimit-Limit': '30',
        'X-RateLimit-Remaining': rateCheck.remainingRequests?.toString() || '0',
        'X-RateLimit-Reset': rateCheck.resetTime?.toString() || ''
      }
    })

  } catch (error) {
    console.error('GET endpoint error:', error)
    return NextResponse.json({
      error: 'Internal server error'
    }, {
      status: 500,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, x-api-key'
      }
    })
  }
}

// OPTIONS handler for CORS preflight
export async function OPTIONS() {
  return new Response(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, x-api-key',
      'Access-Control-Max-Age': '86400', // 24 hours
    },
  })
}